### PR TITLE
New mirror: FZJ

### PR DESCRIPTION
**Pull request by aqw**
Add a NeuroDebian mirror hosted at Forschungszentrum Jülich.

This shouldn't be merged quite yet. I am still populating the mirror manually (from `neurodebian.ovgu.de`). 

Your scripts should rsync to `/var/www/neurodebian.inm7.de/www` (IIRC, those are private and not in this repo). I copied the `.ssh/authorized_keys` from `neurodebian.ovgu.de`, so auth should be good to go.

I'll let you know when the initial rsync is done. Let me know if I'm missing anything. :-)

### CODE REVIEW

**Comment by aqw** [comment]
I forgot to mention: the copy is complete. The travis failures seem to be unrelated.

**Comment by aqw** [comment]
Unsure if you receive notifications, so pinging @yarikoptic :-)

**Comment by yarikoptic** [comment]
Thanks for all the typo fixes!  indeed fail is unrelated and just reminded me that I forgot to start snapshotting service after power down!!!

**Comment by aqw** [comment]
Thanks for the merge! Do you need any more information for your mirror scripts, or is all fo that good to go?

**Comment by yarikoptic** [comment]
well, I stopped carrying (never fully automated, and ran out of time/motivation) to "access mirrors" (beyond the basic sensing), so as long as they work for you should be all good.  I did rebuild website though and it didn't appear on
http://neuro.debian.net/mirrors_status.html#chap-mirrors-stats
but let's give it a day -- may be I forgot to run some command which would run on cron although I thought I did them all

**Comment by aqw** [comment]
Hmm. Seems that the god-of-cron is not in a benevolent mood. The new mirror has not yet appeared. :-/

**Comment by aqw** [comment]
@yarikoptic Still no love for the new mirror. Thoughts?

**Comment by yarikoptic** [comment]
sorry for forgetting about this one... old setup, moved since original location, etc - started to dig only to later realize the problem on top (and somehow I missed that):
```shell
neurodebian@falkor:~/tools/neurodebian$ xvfb-run make upload-website
...
PYTHONPATH=.:3rd/bigmess: 3rd/bigmess/bin/bigmess -c neurodebian.cfg mkmirrorsstat -d build/src
WARNING: Mirror cn-zj is 110 days 11 hours old
WARNING: Mirror de-fzj is 6 days 19 hours old
ERROR: 'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128) (UnicodeDecodeError)
Makefile:52: recipe for target 'source-stamp' failed
make: *** [source-stamp] Error 1

```
So as a quick "fix" I just replaced `ü` with `u` for now in 3198b750d0b81727b06b45269de1ae0cd80615d7 .

System is  stretch , I did install also python3-sphinx (1.4.9-2) not sure if "bigmess" is fully ready for python3 (is it?).  Thus - a lazy fix above for now to close this issue.  All good now

NB -- note that  time stamp comparison states that it is 6 days old, may be cron should be adjusted to run more frequently?

**Comment by aqw** [comment]
@yarikoptic Thanks! nice that it was an easy fix. Re timestamp: IIRC, this is all push based from your server. There's no cron job running on my mirror doing a pull. So the timestamp is correct: it's been 6 days since I last manually rsync-ed from neurodebian.ovgu.de, but now should be kept up to date via your script(s).

Please correct me if I am mistaken.

**Comment by aqw** [comment]
@yarikoptic Nevermind, I found the cronjobs. They were setup by you (or michael), and thus were in the crontab of the `neurodebian` user (I never use crontab, so I didn't think to look there.).

I have setup the cronjob for syncing, so that should be good now.

There is another job for updating the bigmess cache, but those tools are not deployed on this new mirror. I looked on neurodebian.ovgu.de, and they're ancient (from 2013). Is this still necessary?

**Comment by yarikoptic** [comment]
> neurodebian.ovgu.de, and they're ancient (from 2013). Is this still necessary?

that was the new web ui for neurodebian which was never finalized to my picky (well -- I just wanted some feature parity iirc) liking thus never deployed on neuro.debian.net .  I am not sure if it is longer needed.  For a "pure mirror" you just needs cron'ed rsync job to fetch the archive and that is it

**Comment by aqw** [comment]
Thanks! Then I expect the mirror stats to look happy soon... http://neuro.debian.net/mirrors_status.html#chap-mirrors-stats

**Pull request merged**
