### PR TITLE
BF: Switched source discovery from apt-cache to using /var/lib/apt/li…

### LINKED ISSUE #46: nd_freeze: security and updates aren't
Tried on this Singularity file:
```shell
$> cat Singularity.git-annex-dev
Bootstrap:docker
From:neurodebian:buster

%post
    echo "Configuring the environment"
    apt-get -y update

    echo "Freezing the environment"
    nd_freeze 2018/08/08

#    # setup the container sources themselves
#    apt-get -y install eatmydata vim less devscripts

%runscript
    #exec /bin/bash "$@"
    # Or let's just build the beast assuming we are in the directory with git-annex
    # sources
    make linuxstandalone

%environments
    unset PYTHONPATH
```
aforementioned `apt-get install` is commented out since it failed to install anything... so I was curious and thus built image without it to see:
```shell
$> cat /etc/apt/sources.list
# deb http://deb.debian.org/debian buster main
deb http://security.debian.org/debian-security buster/updates main
deb http://deb.debian.org/debian buster-updates main
```
so neither debian-security nor updates got their treatment to be replaced with entries from the Debian snapshots.

### PR DESCRIPTION
**Pull request by mjtravers**
…sts/*Release files

fixes #46 

I am able to successfully install the apt sources files necessary and downgrade the needed packages into a Singularity image. Here's my test Singularity file:

```
Bootstrap:docker
From:neurodebian:buster

%files
	/home/matt/Documents/repronim/neurodebian/tools/nd_freeze /opt/nd_freeze

%post
	#echo "Configuring the environment"
	#apt-get -y update

	echo "Freezing the environment ---------------------------"
	/opt/nd_freeze --debug 2018/08/08

	# setup the container sources themselves
	#apt-get install -y eatmydata vim less devscripts

%runscript
	make linuxstandalone

%environments
	unset PYTHONPATH
```

However, when refreshing the apt cache after creating the snapshot sources files, I am seeing a couple of errors for the debian-security repo. Although, the downgrades look to have been executed okay it looks like there is a key issue:

```
INFO: Refreshing apt cache
W: GPG error: http://snapshot.debian.org/archive/debian-security/20180808T141609Z buster/updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553
E: The repository 'http://snapshot.debian.org/archive/debian-security/20180808T141609Z buster/updates InRelease' is not signed.
DEBUG: Get:1 http://snapshot-neuro.debian.net:5002/archive/neurodebian/20180808T050502Z data InRelease [25.7 kB]
Get:2 http://snapshot-neuro.debian.net:5002/archive/neurodebian/20180808T050502Z buster InRelease [23.9 kB]
Get:3 http://snapshot.debian.org/archive/debian/20180808T024907Z buster-updates InRelease [47.6 kB]
Get:4 http://snapshot-neuro.debian.net:5002/archive/neurodebian/20180808T050502Z data/non-free amd64 Packages [5961 B]
Get:5 http://snapshot-neuro.debian.net:5002/archive/neurodebian/20180808T050502Z data/main amd64 Packages [6579 B]
Get:6 http://snapshot-neuro.debian.net:5002/archive/neurodebian/20180808T050502Z buster/contrib amd64 Packages [14.9 kB]
Get:7 http://snapshot-neuro.debian.net:5002/archive/neurodebian/20180808T050502Z buster/main amd64 Packages [54.4 kB]
Get:8 http://snapshot.debian.org/archive/debian-security/20180808T141609Z buster/updates InRelease [38.3 kB]
Get:9 http://snapshot-neuro.debian.net:5002/archive/neurodebian/20180808T050502Z buster/non-free amd64 Packages [7168 B]
Get:10 http://snapshot.debian.org/archive/debian/20180808T024907Z buster InRelease [150 kB]
Err:8 http://snapshot.debian.org/archive/debian-security/20180808T141609Z buster/updates InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553
Get:11 http://snapshot.debian.org/archive/debian/20180808T024907Z buster/main amd64 Packages [7555 kB]
Get:12 http://snapshot.debian.org/archive/debian/20180808T024907Z buster/contrib amd64 Packages [49.4 kB]
Get:13 http://snapshot.debian.org/archive/debian/20180808T024907Z buster/non-free amd64 Packages [78.0 kB]
```

### CODE REVIEW

**Comment by yarikoptic** [comment]
AWESOME! Thanks @mjtravers . yet to review the code to the best of my perl capabilities ;)

Remark: In df5f0f6e1e0f53bf79b0322b3e680e69954c2eb2 originally we disallowed insecure repos (`--no-allow-insecure-repositories/`), then in ba186e318ff27f02efb92b264547a9615195ad8e change was made to keep it strict only for Debian (if I read the perl right), unfortunately no comment on why it is needed was made and I don't remember the reasoning...

Question: perl -- so if e.g. `qx/apt-get update/` fails (exits with non-0) -- does that lead to the full script erroring out or it just continues to plow through?  if fails we should react/inform IMHO

Re possible Fix: (we ideally should make it all legit to the degree possible)
the key is for a much older debian release (not even pertinent here AFAIK), and was removed from current keyrings:
```shell
$> for ar in /usr/share/keyrings/*gpg; do gpg --keyring $ar --no-default-keyring --list-keys 8B48AD6246925553 2>/dev/null && echo "+$ar" || echo "-$ar"; done                                                                                                   
-/usr/share/keyrings/debian-archive-jessie-automatic.gpg
-/usr/share/keyrings/debian-archive-jessie-security-automatic.gpg
-/usr/share/keyrings/debian-archive-jessie-stable.gpg
-/usr/share/keyrings/debian-archive-keyring.gpg
pub   rsa4096 2012-04-27 [SC] [expires: 2020-04-25]
      A1BD8E9D78F7FE5C3E65D8AF8B48AD6246925553
uid           [ unknown] Debian Archive Automatic Signing Key (7.0/wheezy) <ftpmaster@debian.org>

+/usr/share/keyrings/debian-archive-removed-keys.gpg
-/usr/share/keyrings/debian-archive-stretch-automatic.gpg
-/usr/share/keyrings/debian-archive-stretch-security-automatic.gpg
-/usr/share/keyrings/debian-archive-stretch-stable.gpg
-/usr/share/keyrings/debian-keyring.gpg
-/usr/share/keyrings/debian-maintainers.gpg
-/usr/share/keyrings/debian-nonupload.gpg
-/usr/share/keyrings/debian-role-keys.gpg
-/usr/share/keyrings/ubuntu-archive-keyring.gpg
-/usr/share/keyrings/ubuntu-archive-removed-keys.gpg
-/usr/share/keyrings/ubuntu-master-keyring.gpg
```
(took me awhile to find that --no-default-keyring option to get actual desired result here ;))

So I am not sure why it even complains here, we aren't using wheezy, so how does it "find it"?
I will reproduce and check it out

**Comment by mjtravers** [comment]
This last commit:

1. Downgrades the debian-archive-keyring package explicitly to eliminate the "public key is not available" error message.
2. Tests the apt package version to and adjusts the "apt update" switches accordingly.
3. Fails the freeze when a shell command run by the script returns an error code.

I tried a run on the debian:testing docker image to get a snapshot back to 8/8/2010 but it hit up against a  missing Release file issue:

```
DEBUG: Executing shell command: 'apt-get update --no-allow-insecure-repositories'
E: The repository 'http://snapshot.debian.org/archive/debian/20100808T031154Z buster Release' does not have a Release file.
```

Am still looking into this.

**Comment by yarikoptic** [comment]
That is too far back for buster -- it didn't exist then yet.
The question it why it jumped from 'testing' to 'buster' since there is no buster in the names within apt sources files:
```
$> docker run -it --rm debian:testing
root@6dcc7416ad88:/# grep -r  buster /etc/apt/sources.list*
root@6dcc7416ad88:/# 
```
and it is only listed as Codename within *Release:
```
root@6dcc7416ad88:/# ls /var/lib/apt/lists/
auxfiles							    lock
deb.debian.org_debian_dists_testing_InRelease			    partial
deb.debian.org_debian_dists_testing_main_binary-amd64_Packages.lz4
root@6dcc7416ad88:/# head /var/lib/apt/lists/deb.debian.org_debian_dists_testing_InRelease
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Origin: Debian
Label: Debian
Suite: testing
Codename: buster
Changelogs: http://metadata.ftp-master.debian.org/changelogs/@CHANGEPATH@_changelog
Date: Wed, 12 Dec 2018 09:59:06 UTC
Valid-Until: Wed, 19 Dec 2018 09:59:06 UTC
```
So I guess you just need to go after "Suite" not "Codename"

**Comment by mjtravers** [comment]
@yarikoptic 
The "testing" docker version is actually a pointer to buster. The Suite parameter for a release points to a particular release. At the moment, suite "stable" points to "stretch", suite "oldstable" to "jessie", etc. Back in 2014, suite "stable" pointed to "wheezy" and "testing" to "jessie".

You can see the literal pointers in the snapshot dist directory:
https://snapshot.debian.org/archive/debian/20140901T040302Z/dists/

For the nd_freeze script, is there a use case where the user does not want the release at a paste date but rather the suite? The nd_freeze script could take a "--suite testing|stable|oldstable|oldoldstable" switch, in which case we would ignore the release completely as that would be decided by the suite requested at the particular past date. Would there be interested in being able to do that?

**Pull request merged**
